### ISSUE TITLE
划分sequence_output的问题

### ISSUE THREAD

**Issue by zzy99** [zzshou/RCAM#1]
你好，DUMA的model里，在将sequence_output划分成article_output和choice_output时，不同数据length不同但统一用的是batch内的max length of articles，这样划分是不是不太准确？

**Comment by zzshou** [comment]
你好，感谢提问。
划分的时候我们用max length of article和 max length of choice分别保证序列包含文章和选项。在后序计算attention时，mask的计算我们使用的是每个example的文章长度，对后续不会有影响。
